### ISSUE TITLE
testing non odoo project

### ISSUE THREAD

**Issue by petrus-v** [camptocamp/pytest-odoo#38]
I'm getting following trace back using python 3.8.6 while running test for simple python tests files using the same env that I use to develop odoo project (some bdd tests), In the mean time I've create a dedicated venv for my bdd tests

I'll probably spend some times to figure out how to make this smooth and avoid to complaint where pytest-odoo plugin is not required by my unit tests.

```
../../../.pyenv/versions/3.8.6/envs/jeano386/lib/python3.8/site-packages/pytest_odoo.py:116: in _importtestmodule
    pkgroot = pypkgpath.dirpath()
E   AttributeError: 'NoneType' object has no attribute 'dirpath'
```

**Comment by Jerther** [comment]
For all non-odoo related tests, I add this parameter to disable the plugin when running pytest:

`-p no:odoo`

Hope this helps.

**Comment by petrus-v** [comment]
> For all non-odoo related tests, I add this parameter to disable the plugin when running pytest:
> 
> `-p no:odoo`
> 
> Hope this helps.

oh thanks I didn't know I could disable plugin at launch time. I'll try that next time. So I'm closing this issue.
