### ISSUE TITLE
Since Odoo 15.0, Environment.manage() is useless

### ISSUE THREAD

**Issue by dreispt** [camptocamp/pytest-odoo#40]
When running pytest with Odoo 15, a warning is shown aling with a  with a traceback:

`021-11-04 12:56:10,193 1533666 WARNING ? py.warnings: /usr/lib/python3.8/contextlib.py:113: DeprecationWarning: Since Odoo 15.0, Environment.manage() is useless.`

**Comment by yvaucher** [comment]
closed with #41
