### ISSUE TITLE
Can't Test Controllers

### ISSUE THREAD

**Issue by eselimsen** [camptocamp/pytest-odoo#44]
Hi
First of all, thank you for maintaining this module, it really fills the gap on testing.

I've been using module for a while, maybe more than a year, but still couldn't find a "official" solution for controller testing.
Looks like we're telling Odoo server to exit immediately, then move on to other steps. Since there's no Odoo server to make requests to, I can't test my controllers, I have to spin up another server process and make requests to that server. I made some wrappers and helpers to auto-clean resources created on server process, but it's still far away from perfect, let alone I can't access to logs etc.

I assume you're aware of this, but is there a way to solve this, am I missing something?

**Comment by yvaucher** [comment]
Hi @eselimsen

You might have missed the `HttpCase` class for tests.

``` python
from odoo.tests import HttpCase

class TestController(HttpCase):
    def test_something(self):
        # ...
        result = self.url_open(some_url)
        # ...
```

https://github.com/odoo/odoo/blob/15.0/addons/test_website/tests/test_controller_args.py

**Comment by eselimsen** [comment]
Thanks, I checked that, but I want to test server-side actions, not just responses. It causes leftover records, and I can't check logs (pretty important for me).

However, today I started Mocking request object, like website does [here](https://github.com/odoo/odoo/blob/8e4dfd11b36e81e6609199c6b2d667c4cedee31a/addons/website/tools.py#L67), I'll see how well it does.

**Comment by yvaucher** [comment]
Have you tried using `pytest --odoo-log-level=...`?

**Comment by simahawk** [comment]
@eselimsen HttpCase is not supported yet here.
What I do usually when I want to ensure a route is registered and called properly is to split the tests (sort of unit + integration tests).

Here, [normal tests](https://github.com/OCA/edi/blob/14.0/endpoint/tests/test_endpoint.py#L96) that require a request (mocked with [this](https://github.com/OCA/edi/blob/14.0/endpoint/tests/common.py#L36)).

And here [tests for the controllers](https://github.com/OCA/edi/blob/14.0/endpoint/tests/test_endpoint_controller.py#L19).
Note the decorator `@unittest.skipIf(os.getenv("SKIP_HTTP_CASE"), "EndpointHttpCase skipped")` which allows me to run the whole test suite via pytest w/out breaking, using `SKIP_HTTP_CASE=1 pytest --odoo-database foo [...]`.

**Comment by eselimsen** [comment]
Looks like mocking request is the best for me now, also skipIf looks interesting too, thanks.
@simahawk
