### ISSUE TITLE
How to identify the individual test_module name?

### ISSUE THREAD

**Issue by star128** [camptocamp/pytest-odoo#46]
For Odoo's unittest, it might identify the individual test_module as following:
python odoo-bin -c /path/to/config.conf -d dbname -u test_module --log-level=test

But, for pytest-odoo, how to identify the individual test_module name?
pytest -s --odoo-database=dbname  --odoo-log-level=debug_sql

Thanks

**Comment by simahawk** [comment]
just use the path: `pytest [..] path/to/module/[tests/test_specific_file.py]`
