### ISSUE TITLE
How to use with pytest-xdist?

### ISSUE THREAD

**Issue by dz0** [camptocamp/pytest-odoo#58]
Hi, 

I'd like to use it with [pytest-xdist](https://pypi.org/project/pytest-xdist/), but get Deadlocks because of simultaneus updates.

As I have my fresh DB (with demo data) ready before calling pytest --  
I could automatically copy it for each worker (example [like here](https://github.com/pytest-dev/pytest-xdist/issues/271#issuecomment-825679309)) .

I can get each worker [like](https://pytest-xdist.readthedocs.io/en/latest/how-to.html?highlight=each%20worker#identifying-the-worker-process-during-a-test) [this](https://pytest-xdist.readthedocs.io/en/latest/how-to.html?highlight=each%20worker#envvar-PYTEST_XDIST_WORKER) and use it for separate DB naming.

But how then pass those separate db-names to pytest-odoo separate processes?

**Comment by yvaucher** [comment]
IIUC pytest-xdist will dispatch all tests randomly to workers. Which could be an issue with database transactions.

It would require to make pytest-xdist know about SavepointCase and SingleTransactionCase. As it needs to be aware of when the savepoint and rollback, making it impossible in somecase to parallelize fully a test suite.

For SavepointCase (which nowadays is the default), it would most likely require to distribute the tests to the CPUs after the setupClass is done.

For SingleTransactionCase, it needs to be sequential.

**Comment by yvaucher** [comment]
Check #77
