### ISSUE TITLE
PyPI upload broken

### ISSUE THREAD

**Issue by simahawk** [camptocamp/pytest-odoo#62]
Last release 1.0.1 didn't land yet on PyPI because of
![image](https://github.com/camptocamp/pytest-odoo/assets/347149/17954e3f-b704-437e-a423-e89c238f2ed3)

**Comment by grindtildeath** [comment]
@simahawk Any chance this can be fixed? It's annoying having to force install from git on every 17.0 project?

**Comment by simahawk** [comment]
@grindtildeath I didn't have time TBH, I wanted to switch to GH actions while doing it so that we stay in line w/ what we do on OCA. 

Yet... I had a quick look now and... drum roll.....  et voilá 

https://pypi.org/manage/project/pytest-odoo/release/1.0.1/
