### ISSUE TITLE
module import broken

### ISSUE THREAD

**Issue by Jerther** [camptocamp/pytest-odoo#63]
Hi!!

I was developping modules against oldish odoo 15 code (two months maybe). I recently dit a git pull on Odoo code, and I also had to reset my venv packages to match Odoo's requirements.txt, and now all my tests crash with this error:

`AssertionError: Invalid import of my_module.models.angle.Angle, it should start with 'odoo.addons'.`

To make them work again, I have to modify my modules root `__init__.py` from this:

`from . import models`

to this:

`from odoo.addons.my_module import models`

It seems like `_importtestmodule()` in `pytest_odoo.py` is not run anymore and I'm not sure why. Any clue?

**Comment by Jerther** [comment]
I've got it. The problem starts when upgrading pytest from 7.4.4 to 8.0.0.

**Comment by simahawk** [comment]
It has been fixed on #61 but the publishing on PyPI is broken ATM #62.
You can install from master meanwhile.
